Repository WriteInGesturesProject/dev, pull requests merged in 2021-03, with the labels that each got.

#275 245 Develop an exchange between Godot and our database (POC)
  Proof of concept/API/SpringAPI/src/main/java/com/example/demo/controller/EnfantController.java
  Proof of concept/API/SpringAPI/src/main/resources/application.properties
  Proof of concept/GodotApplicationHTTP/Control.gd
  Proof of concept/GodotApplicationHTTP/Control.tscn
Labels: back-end

#287 Huge commit (see desc.)
  writeInGesture/Global.gd
  writeInGesture/artiphonie/artiphonie.gd
  writeInGesture/artiphonie/artiphonie.tscn
  writeInGesture/artiphonie/goosegame/gooseGame.gd
  writeInGesture/artiphonie/goosegame/gooseGame.tscn
  writeInGesture/artiphonie/learning/learning.gd
  writeInGesture/artiphonie/learning/learning.tscn
  writeInGesture/artiphonie/listenchoose/cardListenChoose.gd
  writeInGesture/artiphonie/listenchoose/listenChoose.gd
  writeInGesture/artiphonie/listenchoose/listenChoose.tscn
  writeInGesture/artiphonie/memory/memoryCard.gd
  writeInGesture/artiphonie/memory/memoryGame.gd
  writeInGesture/artiphonie/memory/memoryGame.tscn
  writeInGesture/main.gd
  writeInGesture/main.tscn
  writeInGesture/page/help/interfaceDescriptionGesture.gd
  writeInGesture/page/help/interfaceGesture.tscn
  writeInGesture/page/home/home.tscn
  writeInGesture/page/navigation/gameChoose.gd
  writeInGesture/page/navigation/gameChoose.tscn
  writeInGesture/page/navigation/gameEnd.gd
  writeInGesture/page/navigation/navigationHelp.tscn
  writeInGesture/page/navigation/sliderSceneHelp.tscn
  writeInGesture/page/navigation/tools/navigationPage.tscn
  writeInGesture/page/syllablestruct/syllableStruct.tscn
  writeInGesture/page/train/drawWord.gd
  writeInGesture/page/train/drawWord.tscn
  writeInGesture/page/train/train.gd
  writeInGesture/page/wordschoice/wordschoice.tscn
  writeInGesture/project.godot
  writeInGesture/shared/artiphonie.gd
  writeInGesture/shared/back/back_button.gd
  writeInGesture/shared/back/back_button.tscn
  writeInGesture/shared/home/home.gd
  writeInGesture/shared/home/home.tscn
  writeInGesture/shared/learning/learning.gd
  writeInGesture/shared/learning/learning.tscn
  writeInGesture/shared/learning/learning_element.gd
  writeInGesture/shared/learning/learning_element.tscn
  writeInGesture/shared/loading/loading.tscn
  writeInGesture/shared/playing/element_difficulty.tscn
  writeInGesture/shared/playing/playing.gd
  writeInGesture/shared/playing/playing.tscn
  writeInGesture/shared/playing/playing_element.tscn
Labels: front-end

#295 add about button as a scene
  writeInGesture/Global.gd
  writeInGesture/artiphonie/artiphonie.gd
  writeInGesture/artiphonie/artiphonie.tscn
  writeInGesture/data/artiphonie/aboutContent.txt
  writeInGesture/page/about/about.tscn
  writeInGesture/shared/about/about.gd
  writeInGesture/shared/about/about.tscn
  writeInGesture/shared/about/about_button.gd
  writeInGesture/shared/about/about_button.tscn
  writeInGesture/shared/home/home.gd
  writeInGesture/shared/home/home.tscn
Labels: front-end

#296 277 Writing documentation about POC with BDD, HTTP, API and GODOT
  Proof of concept/README.md
Labels: documentation

#298 297 memory
  writeInGesture/artiphonie/memory/memoryCard.gd
  writeInGesture/artiphonie/memory/memoryGame.gd
  writeInGesture/artiphonie/memory/memory_card.gd
  writeInGesture/artiphonie/memory/memory_card.tscn
  writeInGesture/artiphonie/memory/memory_game.gd
  writeInGesture/artiphonie/memory/memory_game.tscn
  writeInGesture/main.gd
Labels: front-end

#304 299 game end
  writeInGesture/Global.gd
  writeInGesture/artiphonie/goose_game/goose_game.gd
  writeInGesture/artiphonie/memory/memory_card.gd
  writeInGesture/artiphonie/memory/memory_game.gd
  writeInGesture/artiphonie/utility/pronouncing/pronouncing.gd
  writeInGesture/logs/godot.log
  writeInGesture/project.godot
  writeInGesture/shared/game_end/gameEnd.gd
  writeInGesture/shared/game_end/gameEnd.tscn
  writeInGesture/shared/game_end/game_end.gd
  writeInGesture/shared/game_end/game_end.tscn
Labels: front-end

#310 307 listen and choose
  writeInGesture/artiphonie/listen_choose/card_listen_choose.gd
  writeInGesture/artiphonie/listen_choose/card_listen_choose.tscn
  writeInGesture/artiphonie/listen_choose/listen_choose.gd
  writeInGesture/artiphonie/listen_choose/listen_choose.tscn
  writeInGesture/artiphonie/listenchoose/cardListenChoose.gd
  writeInGesture/artiphonie/listenchoose/listenChoose.gd
  writeInGesture/artiphonie/listenchoose/listenChoose.tscn
  writeInGesture/artiphonie/memory/memory_game.gd
  writeInGesture/artiphonie/playing/playing.gd
  writeInGesture/artiphonie/utility/pronouncing/pronouncing.tscn
  writeInGesture/data/alice.json
  writeInGesture/page/wordschoice/wordschoice.tscn
  writeInGesture/project.godot
  writeInGesture/shared/artiphonie.gd
Labels: front-end

#314 291 avatar space
  writeInGesture/Global.gd
  writeInGesture/art/shopImages/ananas.png
  writeInGesture/art/shopImages/botte.png
  writeInGesture/art/shopImages/bouche.png
  writeInGesture/art/shopImages/chapeau.png
  writeInGesture/assets/theme/themePanelPopup.tres
  writeInGesture/data/alice.json
  writeInGesture/data/shopItem.json
  writeInGesture/entity/Item.gd
  writeInGesture/entity/Player.gd
  writeInGesture/page/avatarspace/avatarSpace.gd
  writeInGesture/page/avatarspace/avatarSpace.tscn
  writeInGesture/shared/avatarspace/avatar_button.gd
  writeInGesture/shared/avatarspace/avatar_button.tscn
  writeInGesture/shared/avatarspace/avatar_space.gd
  writeInGesture/shared/avatarspace/avatar_space.tscn
  writeInGesture/shared/avatarspace/item.gd
  writeInGesture/shared/avatarspace/item.tscn
  writeInGesture/shared/avatarspace/item_type.gd
  writeInGesture/shared/avatarspace/item_type.tscn
  writeInGesture/shared/home/home.tscn
  writeInGesture/shared/playing/element_difficulty.tscn
  writeInGesture/shared/playing/playing_element.tscn
Labels: front-end

#315 293 main menu
  writeInGesture/Global.gd
  writeInGesture/assets/artiphonie/icon.png
  writeInGesture/assets/artiphonie/logo.png
  writeInGesture/main.gd
  writeInGesture/shared/main_menu/app_element.gd
  writeInGesture/shared/main_menu/app_element.tscn
  writeInGesture/shared/main_menu/main_menu.gd
  writeInGesture/shared/main_menu/main_menu.tscn
Labels: front-end

#317 291 avatar space
  writeInGesture/art/avatar/boy1.png
  writeInGesture/art/avatar/boy2.png
  writeInGesture/art/avatar/girl1.png
  writeInGesture/art/avatar/girl2.png
  writeInGesture/art/shopImages/ananas.png
  writeInGesture/art/shopImages/botte.png
  writeInGesture/art/shopImages/bouche.png
  writeInGesture/art/shopImages/chapeau.png
  writeInGesture/art/shopImages/chapeau_haut_forme.png
  writeInGesture/art/shopImages/fleur.png
  writeInGesture/art/shopImages/lunette_lune_bleu.png
  writeInGesture/art/shopImages/lunette_lune_jaune.png
  writeInGesture/art/shopImages/lunette_lune_rouge.png
  writeInGesture/art/shopImages/lunette_lune_vert.png
  writeInGesture/art/shopImages/lunette_ronde_bleu.png
  writeInGesture/art/shopImages/lunette_ronde_jaune.png
  writeInGesture/art/shopImages/lunette_ronde_rouge.png
  writeInGesture/art/shopImages/lunette_ronde_vert.png
  writeInGesture/art/shopImages/tshirt_bleu.png
  writeInGesture/art/shopImages/tshirt_jaune.png
  writeInGesture/art/shopImages/tshirt_orange.png
  writeInGesture/art/shopImages/tshirt_rouge.png
  writeInGesture/art/shopImages/tshirt_vert.png
  writeInGesture/art/shopImages/tshirt_violet.png
  writeInGesture/data/alice.json
  writeInGesture/data/shopItem.json
  writeInGesture/shared/avatarspace/avatar_space.gd
  writeInGesture/shared/avatarspace/avatar_space.tscn
  writeInGesture/shared/avatarspace/item.tscn
  writeInGesture/shared/avatarspace/profilPicture.gd
  writeInGesture/shared/avatarspace/profilPicture.tscn
Labels: front-end

#320 291 avatar space
  writeInGesture/Global.gd
  writeInGesture/assets/GlobalAppLogo.png
  writeInGesture/data/titouan.json
  writeInGesture/shared/avatarspace/avatar_button.gd
  writeInGesture/shared/avatarspace/avatar_button.tscn
  writeInGesture/shared/avatarspace/item.gd
  writeInGesture/shared/avatarspace/item.tscn
  writeInGesture/shared/home/home.tscn
  writeInGesture/shared/main_menu/main_menu.tscn
Labels: front-end

#321 Add the phonetic difficulty in listen_choose
  writeInGesture/Global.gd
  writeInGesture/artiphonie/listen_choose/card_listen_choose.gd
  writeInGesture/artiphonie/listen_choose/card_listen_choose.tscn
  writeInGesture/artiphonie/listen_choose/listen_choose.gd
  writeInGesture/artiphonie/listen_choose/listen_choose.tscn
  writeInGesture/data/phonetic_table_resource.json
  writeInGesture/shared/artiphonie.gd
  writeInGesture/shared/instruction/instruction.gd
Labels: front-end

#323 Fix listen_choose phonetics difficulty and back button pb
  writeInGesture/Global.gd
  writeInGesture/art/borel_maisony/icon/5.png
  writeInGesture/art/borel_maisony/icon/e.png
  writeInGesture/art/borel_maisony/icon/wa.png
  writeInGesture/artiphonie/goose_game/goose_game.tscn
  writeInGesture/artiphonie/listen_choose/listen_choose.tscn
  writeInGesture/artiphonie/memory/memory_game.tscn
  writeInGesture/project.godot
  writeInGesture/shared/back/back_button.gd
  writeInGesture/shared/game_end/game_end.tscn
  writeInGesture/shared/home/home.tscn
  writeInGesture/shared/main_menu/app_element.gd
  writeInGesture/shared/playing/playing.tscn
Labels: front-end

#313 301 Upgrade security with HTTPS requests from Godot (POC)
  Proof of concept/GodotApplicationHTTPS/Control.gd
  Proof of concept/GodotApplicationHTTPS/Control.tscn
  Proof of concept/GodotApplicationHTTPS/default_env.tres
  Proof of concept/GodotApplicationHTTPS/icon.png
  Proof of concept/GodotApplicationHTTPS/project.godot
  Proof of concept/README.md
Labels: back-end
