Repository WriteInGesturesProject/dev, pull requests merged in 2021-02, with the labels that each got.

#265 big commit (see desc.)
  writeInGesture/Global.gd
  writeInGesture/android/AndroidPermissions/src/AndroidPermissions.java
  writeInGesture/beginScene.gd
  writeInGesture/beginScene.tscn
  writeInGesture/main.gd
  writeInGesture/main.tscn
  writeInGesture/page/loading/loading.tscn
  writeInGesture/project.godot
  writeInGesture/tools/ManagePermission.gd
  writeInGesture/tools/ManagePermission.tscn
  writeInGesture/tools/ManageScreen.gd
Labels: front-end

#267 Fix the about section
  writeInGesture/data/aboutContent.txt
  writeInGesture/page/about/about.gd
Labels: enhancement

#273 Add replay button
  writeInGesture/page/navigation/gameEnd.gd
  writeInGesture/page/navigation/gameEnd.tscn
Labels: enhancement, front-end

#270 244 Develop a little Godot application (POC)
  Proof of concept/GodotApplicationHTTP/Control.gd
  Proof of concept/GodotApplicationHTTP/Control.tscn
  Proof of concept/GodotApplicationHTTP/default_env.tres
  Proof of concept/GodotApplicationHTTP/icon.png
  Proof of concept/GodotApplicationHTTP/icon.png.import
  Proof of concept/GodotApplicationHTTP/project.godot
Labels: back-end
